#+title: ORG Blog Forge
#+setupfile: ./theme-readtheorg.setup
#+export_file_name: index
#+property: :results output :exports both
#+author: Vipul
#+date: <2024-08-12 Mon 08:14>

* Forge your blog using Org-mode, org-roam v2, and GitHub Pages!
Static site generator for Org-roam knowledge bases with automatic CI/CD deployment.
- [[https://orgmode.org/][ORG mode]] | [[https://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html][Org export dispatch Publish]] | [[https://pages.github.com/][Github pages.]]
*  Features
- [X] Org-roam v2 compatible - ID-based bidirectional links
- [X] Automatic publishing - Git push → live site in 3 minutes
- [X] GitHub Actions CI/CD - Zero server maintenance
- [X] Custom themes - any org theme can be applied.
- [X] Responsive design - Mobile-friendly
- [X] Fast builds - Optimized for knowledge bases
* Live Demo
- https://justvipul.github.io/Org-Blog-Forge/

* Steps to start
** Fork this repository

#+begin_src bash
  git clone https://github.com/justvipul/Org-Blog-Forge.git
  cd Org-Blog-Forge
  git remote rename origin upstream
  git remote add origin https://github.com/YOURUSERNAME/YOURREPONAME.git
#+end_src
** add your notes

create .org files in the [[file:notes/][notes/]] directory.

#+begin_src org
:PROPERTIES:
:ID:       unique-id-here
:END:
,#+title: My First Note
,#+date: [2026-01-16 Fri]

,* Content
Your knowledge base content here.

[[id:other-note-id][Link to other note]]
#+end_src
** Push and deploy 

#+begin_src bash
  git add .
  git commit -m "Add my notes"
  git push origin master

#+end_src
* GitHub Actions automatically:
+ Builds your site

+ Publishes to gh-pages branch

+ Deploys to GitHub Pages
* Customisation
Add theme to your [[file:notes/][notes]]

#+begin_src org
#+setupfile: ../gray-theme.setup
#+end_src

Or globally in [[file:build.el][build file]]

#+begin_src emacs-lisp
:html-head "<link rel=\"stylesheet\" href=\"gray-theme.css\"/>"
#+end_src
* Build Configuration
** Edit [[file:build.el][build.el]] for:

- Custom sitemaps

- Publishing rules

- HTML templates
* Static Assets
Place CSS/JS/images in repo [[file:][root]] or [[file:notes/][notes/]] - automatically copied to [[file:public/][public/]]
* Project Structure

#+begin_src bash
  ├── build.el
  ├── build.el~
  ├── LICENSE.txt
  ├── notes
  │   ├── 20260115192033-first_knowledge_base.org
  │   ├── 20260115192033-first_knowledge_base.org~
  │   ├── 20260115192203-linux_tips.org
  │   ├── 20260115192203-linux_tips.org~
  │   ├── 20260115215840-org_mode.org
  │   ├── 20260115215840-org_mode.org~
  │   ├── 20260115215916-basics_and_learnings.org
  │   ├── 20260115215916-basics_and_learnings.org~
  │   ├── 20260115215958-org_modern_test.html
  │   ├── 20260115215958-org_modern_test.org
  │   ├── 20260115215958-org_modern_test.org~
  │   ├── 20260115220057-zathura_imp_keys.org
  │   ├── 20260115220057-zathura_imp_keys.org~
  │   ├── 20260115224949-org_mode_themes.html
  │   ├── 20260115224949-org_mode_themes.org
  │   ├── 20260115224949-org_mode_themes.org~
  │   └── index.org
  ├── org-html-themes
  │   ├── bigblow_inline.theme
  │   ├── comfy_inline.theme
  │   ├── darksun.theme
  │   ├── gray.theme
  │   ├── imagine_light.theme
  │   ├── latexcss.theme
  │   ├── readtheorg_inline.theme
  │   ├── rethink_inline.theme
  │   ├── retro_dark.theme
  │   ├── simple_gray.theme
  │   ├── simple_inline.theme
  │   ├── simple_whiteblue.theme
  │   ├── simple_white.theme
  │   ├── solarized_dark.theme
  │   ├── solarized_light.theme
  │   ├── stylish_white.theme
  │   └── white_clean.theme
  ├── public
  │   └── index.html
  ├── README.org
  ├── rss-to-be-added-study.org
  ├── style.css
  └── theme-readtheorg.setup
  4 directories, 43 files
#+end_src
* local development
#+begin_src bash
  # Install dependencies and build
  emacs --batch -l build.el -f org-publish-all

  # Preview locally
  firefox public/index.html

  # Clean rebuild
  rm -rf public/ .org-timestamps/
  emacs --batch -l build.el -f org-publish-all
#+end_src
* Themes included
#+begin_src bash
  $ tree ./org-html-themes/.

  ./org-html-themes/.
  ├── bigblow_inline.theme
  ├── comfy_inline.theme
  ├── darksun.theme
  ├── gray.theme
  ├── imagine_light.theme
  ├── latexcss.theme
  ├── readtheorg_inline.theme
  ├── rethink_inline.theme
  ├── retro_dark.theme
  ├── simple_gray.theme
  ├── simple_inline.theme
  ├── simple_whiteblue.theme
  ├── simple_white.theme
  ├── solarized_dark.theme
  ├── solarized_light.theme
  ├── stylish_white.theme
  └── white_clean.theme
#+end_src
* Contributing

+ Fork the repo
+ Create feature branch: git checkout -b feature/amazing-theme
+ Commit changes: git commit -m 'Add amazing theme'
+ Push: git push origin feature/amazing-theme
+ Open Pull Request
* TODOS
- [ ] Add RSS Functionality
  [[file:rss-to-be-added-study.org][rss adding learnings]]
- [ ] check if [[https://github.com/protesilaos/denote][denote]] can be used for [[https://onlyvip.github.io/Org-Blog-Forge/][ORG Blog Forge]].
- [ ] Suggestions
- [ ] make [[file:README.org][README]] just a landing page for all steps list.
- [X] [[file:notes/20260115215958-org_modern_test.org][org test file]]
- [X] results are populated in the public folder.
* references
Thanks to
** [[https://github.com/jethrokuan][Jethro kuan]]
** [[https://github.com/fniessen/org-html-themes][Fabrice Niessen]]
** [[https://github.com/spudlyo/orgdemo2][spudlyo]]
** [[https://github.com/minad/org-modern][minad for example.org file]]
** [[https://github.com/protesilaos][prot :)]]
** [[https://github.com/karthink][karthink]]
** [[https://orgmode.org/][org mode]]
** [[https://www.orgroam.com/][org roam]]



* License

MIT License - see [[file:LICENSE.txt][LICENSE]] © 2026 Vipul

