:PROPERTIES:
:ID:       8c3e6cad-40c4-49ff-a042-913a715289b0
:END:
#+title: kavnai trek 31 jan 2026
#+Author: Vipul
#+DATE: <2026-01-31 Sat>

** Schedule
*** went with 4 people today - anil pethkar, bapu sonje, nandkumar kashelani
*** woke at 5
*** bath done at 5.35
*** left home by 6.05
*** left hdfc bank chandak Circle by 6.25 with bapu sonje
*** reached and left decathlon by 6.42 am
*** Datta Mandir 
*** kamakshi mandir
*** started at 7.23
** kamakshi devi mandir
** on da patta
** vishramgadh
** information 
राज्याभिषेक सोहळ्यानंतर (स्वराज्य) स्थापन झाले. अशी एक श्रद्धा आहे की शिवाजी महाराजांनी गुप्तपणे या किल्ल्याला भेट दिली होती.

जवळचे धार्मिक स्थळ, कपिलधार तीर्थ, महान संत ज्ञानेश्वर आणि गजानन महाराज यांच्या पदस्पर्शाने पवित्र झाले.

रामायणाच्या काळात, भगवान हनुमान द्रोणागिरी पर्वत घेऊन जात असताना 'कालनेमी' नावाच्या राक्षसाने त्यांचे लक्ष विचलित केले होते. भगवान हनुमानांनी याच पर्वतावर त्या राक्षसाचा वध केला. म्हणूनच या पर्वताला हे नाव पडले.

कवनई हे ऐतिहासिक आणि वारसा स्मृतींना उजाळा देते.
** facts
type of fort? - hill fort
best season - winter summer rainy

Way to the fort: Climbing from a pathway at the South of Kavnai village

Time to climb: 2 hours / half day trek

Difficulty level: Easy

Spread: Medium

Water availability: Not suitable for drinking

Carry along: No special equipments

Guide: Not necessary
Details

Region: Igatpuri

Base Village: Kavnai

Distance from Nashik: 40 km

Range: Igatpuri range, Sahyadri Sub-range

Height: 2998 ft. from M.S.L
** route to take from nashik - 
from nashik - ghoti road - turn right to vaitarnadam road - from waaki village 1.5km turn right - kavnaigaon will be reached after 4.5km.
** experience -
cool breeze over the massive fort makes you relish every moment spent here. it is a small fort with a temple and the clear waters of the lake dotting the  ladscape. the temple of the goddess kamakshi reflects in the clear waters and so do the clouds in the sky aobve. a shivling with a nandi in front is a temple beside the lake.

there is one cave which is at the right side on the top of the fort. there is one bastion on west side of the fort. one can see the kalsubai range, trimbak range, tringalwadi and otehr forts from the top of this fort. the rays reflected in the clear water of upper vaitarna dam leaves one awestruck.

iron adder now for vonvenient climbing to reach the entrance door. 
** an easy trek for beginners.
** not to miss
*** door at the entrance north side.
*** small caves
*** kavnai devi temple
*** buruj and historical remains on south side 
*** water tank
*** temple of shiva with nandi in fron.
*** bastion on west side. 
*** view of vaitarnadam / mukne dam.
** kavnai village near ghoti - 250 houses.
** kapildhara gajanan maharaj mandir.
*** food facility at kapildhara gajana maharaj mandir as prasadam from 10 am to 6.30 pm daily.
** no facilty at for
** major foodcrops here are rice and barley.
** auto repair at ghoti
** petrol at ghoti and igatpuri.

