:PROPERTIES:
:ID:       6596772d-a333-494b-866e-55889ddf6fad
:END:
#+title: Paachya <2026-03-29 Sun>
#+setupfile: ../org-html-themes/gray.theme

* Trek Overview
1. Trek Name: Paachya
2. Region: Trimbakeshwar
3. Range: Trimbakeshwar
4. Base Village: Jategaon
5. Height from MSL (ft): 1300 ft
6. Type:
   - [ ] hill fort
   - [ ] forest trail
   - [ ] plateau
   - [X] dongar
7. Difficulty Level:
8. [ ] easy
9. [ ] moderate
10. [X] difficult
11. Best Season:
12. [X] winter
13. [X] summer
14. [X] monsoon
15. Time taken to Climb [hrs]: 1 to 1.5 hrs.
16. Water Availability:
17. [ ] yes
18. [X] no
19. Suitable For:
20. [ ] beginners
21. [X] regular trekkers
22. [X] families

* Schedule & Companions
1. Date:  <2026-03-29 Sun>
2. Team Members:
   1) vipul
   2) nidhi
   3) malti bhavsar
   4) snehal deo
   5) sandeep deo
   6) sanjeev rairikar
   7) dattatray gawali
   8) shishikant vadaje
   9) mukund patil
   10) sunil jagtap
   11) bhaskar dhakrao
   12) D. aher
   13) vinayak ratnaparkhi
   14) shyam kashimire
3. Wake-up Time: 5:30 am
4. Left Home: 6:20 am
5. Start Point / Meeting Place: ABB circle.
6. Route Start Time: 7:17 am
7. Return Time: 10 am.
8. Key Stops / Temples / Checkpoints:
   - temple at the bottom.
   - one more mandir while going to jategaon.

* Route Information
1. Route from Base City: ABB circle -> talegaon phata -> talegaon -> jategaon -> both paachya and supacha
2. Final Village Distance km: 17 
3. Public Transport Availability: bus 
4. Parking / Auto / Petrol:  at anjaneri.

* Historical / Mythological Background
1. Historical Importance:
   - no historical records found for these hills.
2. Legends / Myths:
   - none
3. Nearby Heritage / Religious Sites:
   - jategaon, anjaneri.

* Key Landmarks & Attractions
1. Temples:
   - on temple at the bottom.
2. Structures (Bastions, Caves, Gates, etc.):
   - none.
3. Viewpoints (Ranges / Dams visible):
   - waldevi dam view.
4. Not to Miss:
   - mountain range view,

* Experience & Observations
1. Weather / Terrain: weather was clear. long range view.
2. Notable Sights: waldevi dam view.
3. Personal Experience: trek was hard everyone still all it quite well. lot of karwande plants on the ridge line. but it has thorns so use full sleeve. and keep a knife.
4. Vibe / Mood of Place: peacefull calm.
5. Tips for Future Trekkers: follow the ridge line instead of taking the right or left paths.

* Facilities & Amenities
1. Food / Water Availability: none
2. Accommodation / Prasadam Timings: in the village or anjaneri.
3. Shops / Auto Repair / Petrol Info: none.
4. Guide Needed:
5. [ ] yes
6. [X] no

* Local Notes
1. Village Population / Details: 6000
2. Major FoodCrops: jowar, bajri, karwande, brinjal, pulses.
3. Local Culture / People: -

* Photos & Media
1. [X] Add photos
   1) https://i.postimg.cc/z3mrHVTP/photo-2026-03-29-17-43-48.jpg
   2) https://i.postimg.cc/NGK2XS1q/photo-2026-03-29-17-43-49-(2).jpg
   3) https://i.postimg.cc/qBN6KS8f/photo-2026-03-29-17-43-50-(2).jpg
   4) https://i.postimg.cc/PfCvD9mj/photo-2026-03-29-17-43-52.jpg
   5) https://i.postimg.cc/05zKSFp1/photo-2026-03-29-17-43-53.jpg
   6) https://i.postimg.cc/8k7fv9hN/photo-2026-03-29-17-44-00.jpg
   7) https://i.postimg.cc/dQhZCp8J/photo-2026-03-29-17-44-00-(2).jpg
   8) https://i.postimg.cc/VsJ0tpjk/photo-2026-03-29-17-44-04.jpg
   9) https://i.postimg.cc/h4XQm69j/photo-2026-03-29-17-44-07-(2).jpg
   10) https://i.postimg.cc/h4XQm69h/photo-2026-03-29-17-44-15.jpg
   11) https://i.postimg.cc/VsJ0tpjS/photo-2026-03-29-17-44-16.jpg
   12) https://i.postimg.cc/nVX9mgvj/photo-2026-03-29-17-44-25.jpg
   13) https://i.postimg.cc/pVm5j4D5/photo-2026-03-29-17-44-27.jpg
   14) https://i.postimg.cc/ryDR43S4/photo-2026-03-29-17-44-33.jpg
   15) https://i.postimg.cc/xjXNmhKL/photo-2026-03-29-17-44-34.jpg
   16) https://i.postimg.cc/QNFK7wpp/photo-2026-03-29-17-44-35.jpg
   17) https://i.postimg.cc/kML6vscR/photo-2026-03-29-17-44-36.jpg
   18) https://i.postimg.cc/tR8ZNk5P/photo-2026-03-29-17-44-39.jpg
   19) https://i.postimg.cc/9XsRYbpG/photo-2026-03-29-17-44-40.jpg
   20) https://i.postimg.cc/G368xKQP/photo-2026-03-29-17-44-42.jpg
   21) https://i.postimg.cc/CM9Bs7Ns/photo-2026-03-29-17-44-55.jpg
   22) https://i.postimg.cc/3rz4F1B9/photo-2026-03-29-17-45-00-(2).jpg
   23) https://i.postimg.cc/jqBw4cX8/photo-2026-03-29-17-45-05.jpg
   24) https://i.postimg.cc/sfbQ4mcL/photo-2026-03-29-17-45-13.jpg
 
2. [ ] Add route map (GPS screenshot)
3. [ ] Add group photo

* Reflection
1. What I Loved Most: the ridge line and the surrounding view.
2. What I’d Improve Next Time: nothing.
3. Recommend To: beginner and advance trekkers. 
4. Return Visit:
5. [X] yes/no
6. [ ] (why?)
short hike, amazing view, temple at the bottom. 360 degree view of all the mountain ranges.

