:PROPERTIES:
:ID:       7ad239fd-324d-4361-a81c-e8ee889a148c
:END:
#+title: The Age of Enshittification

In a new book, the technology critic Cory Doctorow expands on a coinage that has become bleakly relevant, in Silicon Valley and beyond.
By Kyle Chayka
October 1, 2025
Illustration by Nicholas Konrad

You’re reading Infinite Scroll, Kyle Chayka’s weekly column on how technology shapes culture.
Sometimes a term is so apt, its meaning so clear and so relevant to our circumstances, that it becomes more than just a useful buzzword and grows to define an entire moment. “Enshittification,” coined by the prolific technology critic and author Cory Doctorow, is one of these. Doctorow came up with the phrase, in 2022, to describe how all the digital services that increasingly dominated our daily lives seemed to be getting worse at the same time. Google Search had become enshittified, showing ads and product links instead of relevant website results. TikTok had become enshittified, artificially “heating” specific videos so that some would go viral, inspiring copycats and goosing engagement while frustrating creators whose output didn’t get the same treatment. Twitter would soon become royally enshittified in its reincarnation as X, losing its status as a global town square, as it tipped into Muskian extremism and rewarded grifters and meme accounts over legitimate news sources. Spotify, iPhones, Adobe software, e-mail inboxes—it was hard to think of a platform or device that wasn’t seeing a decay in user experience. Wasn’t technology supposed to endlessly improve in the long run? All of the counterproductive corporate interference brought to mind a Silicon Valley boondoggle from 2017, when a company called Juicero raised more than a hundred million dollars to build a juice-pressing machine whose proprietary bags, it emerged, could just as easily be squeezed out by hand—an enshittified appliance par excellence.

“Enshittification” was named the word of the year by the American Dialect Society in 2023 and by Australia’s Macquarie Dictionary in 2024. The embrace of the term reflected a sense of collective frustration. Technology was improving, after a fashion, but too often those improvements made platforms more adept at extracting value from users and clients, driving profit and engagement for the companies themselves. The worse the Facebook experience got, the more Meta eked free labor from content creators while retaining revenue from advertisers. Uber eventually reached profitability by algorithmically manipulating the rates that drivers were paid, and by conditioning users to lower their expectations; the ride-hailing app even became riddled with ads. Musk’s X, reduced to a bot-filled hall of right-wing conspiracies, could leverage its data as training fodder for Musk’s own artificial-intelligence company.

In Doctorow’s argument, enshittification was an intentional pattern on the part of the tech companies. In his new book of the same name, he expands his various blog posts and articles on the subject into an over-all theory of “why everything suddenly got worse and what to do about it,” as the subtitle puts it. Enshittification unfolds in three phases: first, a company is “good to users,” Doctorow writes, drawing people in droves, as funnel traps do Japanese beetles, with the promise of connection or convenience. Second, with that mass audience consolidated, the company is “good to business customers,” compromising some of its features so that the most lucrative clients, usually advertisers, can thrive on the platform. This second phase is the point at which, say, our Facebook feeds fill with ads and posts from brands. Third, the company turns the user experience into “a giant pile of shit,” making the platform worse for users and businesses alike in order to further enrich the company’s owners and executives. Facebook’s feed, now choked with A.I.-generated garbage and short-form videos, is well into the third act of enshittification. So is TikTok, which has cluttered its interface, to the point of distraction, with e-commerce, in an attempt to compete with Amazon—which has also enshittified its marketplace search results, promoting nonsense brands.

Perhaps we were expecting too much from the digital platforms that we inhabit. The experiences we enjoyed in the early days of social media and on-demand apps turned out to be unsustainable; the services that were initially free or subsidized would have to pay for themselves eventually. The dream of the early, more open internet was that people would connect with one another with minimal mediation, and Doctorow enumerates the structural factors that guarded against enshittification in that era. They included moral pushback from tech workers, who were once in such high demand that they could hold their corporations hostage with the threat of quitting, and the enforcement of monopoly regulations, which discouraged companies such as IBM and Microsoft, in decades past, from turning the screws too hard on their users. Those protective barriers have eroded, but users have also been complicit in their own exploitation. Some of the same features that make apps so convenient, such as on-demand service or instant purchases, also make them easier to abuse. Uber can instantly adjust what it charges consumers and what it pays contractors, a trick that Doctorow calls “twiddling.” The platform’s algorithms are designed to manipulate us into engaging, and too often we do, even against our better interests. Uber drivers who take every gig offered to them out of an “indiscriminate desire to please the algorithm” are actually “signaling that they are easy pickings” who will work for “sub-starvation wages,” Doctorow writes.

One underrated exit strategy for those weary of enshittification is opting out: we users can bail on platforms that commodify our passive participation and give us little in return. There are apps and platforms that are more equitable, whether Bluesky for social media without the rampant toxicity, or Curb for on-demand taxis without the labor violations. But Doctorow doesn’t seem to put much stock in the plausibility of a mass exodus from enshittified platforms. Instead, he focusses on structural change, offering legal and technical cures ranging from better enforcement of antitrust laws to breaking down tech conglomerates to regulating the harvesting of personal data so that users have more robust rights online. On this last front, there is cause for optimism: new laws in the United Kingdom and the European Union are forcing tech companies to treat users in those regions better, which in turn could improve conditions around the world, since it’s simpler for a company to build a single, unified version of their products than many locally customized ones. But American businesses invented many of these problems, and so far the American government is doing little to fix them.

“Enshittification” is a pointed and efficient text, driven by Doctorow’s snarky prose, which reads like what it is: professional blogging extended for three-hundred-plus pages. The book covers a lot, but it leaves the reader craving a grander application of his concept to other aspects of culture and society. A very brief conclusion asks, “Is Enshittification Just Capitalism?” The answer is yes, Doctorow argues, in that our current economic system allows the “enshittification lever” to be cranked toward extraction unchecked. What would truly halt that process is a dismantling of Silicon Valley’s style of self-dealing startup investment, which has resulted in a class of billionaires who feel that they are qualified not only to run companies but to direct political parties and federal agencies. The book stops short of fully extrapolating enshittification to national politics, but the term is certainly also relevant in that realm. If the playbook Doctorow describes involves promising benefits to people only to erratically renege on, and degrade, existing services, then Donald Trump is the enshittifier-in-chief. Under his second Administration, scientific research, diplomacy, corporate watchdogging, and social services have all gotten worse. The beneficiary, of course, is largely Trump himself. Perhaps the worst outcome of enshittification is that it drives us to expect things to be bad, and to assume that they will only get worse

